#!/bin/sh
#
# Perform necessary undrop-for-innodb setup steps
# after package is installed.
#

PROGNAME=`basename $0`

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

for ep in c_parser stream_parser
do
    if ! test -L /usr/bin/${ep}
    then
        ln -s "/opt/undrop-for-innodb/embedded/bin/${ep}" /usr/bin/${ep}
    fi
done

echo "Thank you for installing undrop-for-innodb!"

exit 0
